language: go
go:
- 1.8
env:
  global:
  # this will not work on a PR btw
  - VERSION=1.7.1-beta.2-${TRAVIS_COMMIT::9}
  # DOCKER_EMAIL
  - secure: cdThkr3I+9Tmh1+myIo04yGeHbGkrGe/jh30YIf4L7m4W7NVMgs97zY++h7ffHNl+5wVoIS4dcIe3+Fyw0azVrbxjMXMgE4HJ+Rhga/TXkAURmMSDAwuk4L+d4qZ2LhZI2t2BEPj5gVg/e2Xw5yT8fEFuFPlog06ENuiTwt9WGlIzV0dujl/kl3KE/vwRrXeSeRyeXZCqKL2Bx/t7pi9NeeyYWkJXrGugrxLgx7Q+o+Hh+o/scNmKdvf3ioOwC1lAxINBR6caIu2Fj17CjIB1uCe1baA8Jsv508IyI1mpZe9u64+dmRflKNZBNeIUh5sX9RA5jGkXnqxWdrBFTUVoB8+OkygF9tLBN1Xv348zlu4XSR0ctefILVzLVCdSD1XRP9ykrzliCgxU1ZkUttU+hLol9mFGgZgChSQzkhC2Y0rH1tb99Qe3iptTvGnzT/oZlGnagj6GdcY9YyWXbXH4iYYMkcPqnwELysqP1epQwt9Ca+zSRUzaZZjb7AUg3RoAr0tBuPkDrbpenqSXftCwWVG3LuNszXcbNpCN642hp/bRuOJu67VPpHN5wzCoQbtJric78V5iWEbnwkQ+fy8a21fFuOiA0Q8Yz1gYKMFROycocCb6wzgv2PlcjdUjWukvwHvLvg3hGauBrnKmnIs/WjDne4TFeF/eFdRDuiHgj0=
  # DOCKER_USER
  - secure: Pjm8uB8vZP17J1nuRC6UaigR6sv286jBjxJw71yjGvbDsl65N1zum0uTQ2ZrX1KB6lmiG/veSBSsIQqLtGwfL3JnpjxCePohGfOm81eWhmRkNQ19mVRe3VU/JInBMA8Y2DyYJOfV6i0Vs1byb+WvhgCd+20ThD7xkuncNg5oq9mYOLH4SPNs4QzJUgGqw+GNqzJ9MZGMbXkMEkb9Ao+38ak66GwBq19KfxgCzQPRxtjqkUKyWYtEZZ3a463r4fYPbyuNEuztKel1Ba+smHdgGodVAj8T79/Z8cGRJt/nGoiWn+uguV1SG5jn4yxZTGqfll8njDRlqGR2Zfuj+4irFUojI/N1UAX4NI7JKd9ELqAobAHnn+RUs9X7omJ6ycuZm0rvXetFxYZdeHisn2z+qOa9DrrXPBigYXRe9y3QyOw6NX4NNjsavTj/1U+MGpnzVMefaVfAugi4TTCqXTJWA1ltIGLSfjdwUlmmmaQoW34sZhtDmiK+PU7djR/wfNf1Wgmvo9oiW3WWtHYxRzwvGYC0eBCpFwxBBkacLFayVF3Kg04GD3QaQQr6poUPAhBjEv1GWW2PeTYuHQXHEHDWsdplVnj/Y+g8aOZpcH79KAQcIHjXKfUiv8YLxRTUKPmGMpTeY7JRQ7xQe+KGz0ct3PIjAtKy5RFNr/ZF7R6pifw=
  # DOCKER_PASS
  - secure: DauP2Lv+VRWZHmL0l3hOh/DU6lX6W2iuoCg9BanavhNN6+CGJuTBujb/vQ4xyQKQPD2Et/+2OVH8aRG7521Q9xY5eo1etKlUev0nmN3P3cGjy7u9iM+xSWDeW/DS79OBD12D1svQq97oh+NgdElDSZo83EeNX+vpqCyudbCHEDbEkbgI87XSeD4Yg1GXcN2l3A7AIJrARZOrsiHMcUupEKngUVMbzfZpkJKKzcwdGulPFEgMBmf3PfpSuw1uVF4OvAjXCk+aygIgq9tHtC4svhEhqOJGGONG1w+Klf88sb9m20cuKvoxt4S/qjyeUPNkviZk6/he7GnP0Rn/7voIIdk3uQ05mNLZLOHwLJr8aBAUm9DsLWTSQNZk6+f7ObUE3eHpG0ioqr4ggbzx7Exd7w3H69CER9YsD7TaSP8ecfKy8eNPYeCHRHakSXx4jsgrwQnCfzuTfd2jOx6ywao1AxhgkyrossldYp6TIFDBkkxzmqbb/mfC5OlWHLUcmv4uo03/eI8z/w97wqsPfseqftgF0xBHHCvU2FNi1j9ZgwOYjoAqn+fElhcxLRypGlBYfoMH2P0u0eX9k4y3dfjBhr3blDU+85oyXKCXwohYTNMLOws+JcNn5pFBbZolXePVoqhUENeROx3y341cLgBUpdndIu0/5mi2l18XkBiEyAI=
go_import_path: k8s.io/kops
script:
- make ci
git:
  submodules: false
sudo: required
services:
- docker
after_success:
- make version-dist
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- if [ "$TRAVIS_BRANCH" == "k8s-for-greeks-integration" ]; then DOCKER_REGISTRY=$DOCKER_USER make protokube-push-no-build; fi
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id:
    secure: uoeDFcDxvq6/R31yHG6vT/2iD4ym5JYIU6VEVc8NCGQqDO77K+iUHd0Ga61so1x/MtKBEdUngsIw/2fves6XDQOmK0Piz3rWFdhYELtNIhdmqiY5UzxY9dF2gKorieNpIBmtWswqxS3Q98AsvZ4wtAyHtVViGQf2LPd7niZggyFVJQdxJstI/kMBTZuM+Dm9calyZ7XHV/mRq0n7tshHAwXpmRTDSRR0QvqmM4gAz6qHL+25dOrzv/6NsI20AyxnwIUpUq3kANVLSUVJirehzK4seYCvzZkzj1wVAn7sZCEvAhW94GIw5VdlyoFlZkeT9Sjg1SeH/LWx/ig0czu3lnhNnixEWWvD62Ut+KjzRy0QDwp2K2MrYONPe4nv0bTLCegiVfW5LmQjK9ujIjfvJwGZmJlvHjVuSLXIB2WHCFjH+dRjrsyn8I1iKe2XaPUx0DxroH9bIYjm/nY5G05y25SV1rLQH5oMKwj9Wf11lP7+5jjstFJd+L/XBfsFBmn818z4neJte74nkAOstVWGHpWDGuIn0UYB3bMgwDJ0EcZRQanCTmO19BQIXChK6Gn4EmPEFHejLY2iiclkNJIyiSqEkelQ/UV9ajclDXs1Zds3JQP8wvn8K8rKQfcuPyK3W7O/kqeFNbyxqA5GvaV87CWvA58ejOCpWpMKKxtQJxk=
  bucket: k8s-for-greeks-kops
  local_dir: "$GOPATH/src/k8s.io/kops/.build/upload"
  secret_access_key:
    secure: qzgCIesaBDwCkSTgw787KxPtqfyl9NZ3D85y8As9yeGmG1jZ8eXV3fCrfKLh5427QTzxtjX+5kLk1AG1GX/FxyI++//srd4IGP7BzWkA7PrQ/n7gzqcXvp/tnDWLxGBCycUludI+QehNDIWDG8x1zmqf8WKZ2DM5vHKLw9n533+7brkKovynd1w+lPdfhcB2cZjp4i2grj7bIYyKD0eldtmHUusafJfVT8QCY0XjfO8apv2PeAYdsO0d56gHCmid/0OV4MQpIFMNOKRkC/v5WEsNjP6xOR9PRlETJ6IIY+1P62lJkswqrL3oI65qAgVLR8g+IRySr4Ujx3fEfDq4pvzrm6k9BKu+ScuXRgx9kuRsznScAtOtojeJAuMxxl7mzkD9Q7GZioKfCzn9pN4OBE5UsfCSNwPC58Tb1shpnHHFkod/DTRpP/1//7FKF56CeYIk5yjNWlRNJSFyI5KZWWZIUOBUahrckCOCJCHuHsAWO+U1IrcKL2GEqyl/3y+bqwep1Wdbh+KwDRiRgM6etkKeSLu5TH3RU7b4zbHUbGhKJ323fj8UV4dIgekOfFKNPNdNr/yvbaeFLnbk23Mu8qz11yeqbMSEIXvuC23zsdNtwD/R9A1BILrHiIrae2SkPgqo773ge9F+FQhoV7lluNrwXv3o/S06a2ThLTP1IKA=
  acl: public_read
  on:
    branch: k8s-for-greeks-integration
